---
- name: Install git
  apt:
      name:
      - git

- name: Install global git configuration
  copy:
    src: gitconfig
    dest: /etc/gitconfig
    mode: 0644
    owner: root
    group: root

- name: Install global gitignore configuration
  copy:
    src: gitignore
    dest: /etc/gitignore
    mode: 0644
    owner: root
    group: root
