---
- name: Install sway stuff
  apt:
      name:
      - foot
      - fonts-dejavu

- name: ensures /etc/xdg/foot/ dir exists
  file:
    path: "/etc/xdg/foot/"
    mode: 0755
    owner: root
    group: root
    state: directory

- name: Install foot configuration
  copy:
    src: foot.ini
    dest: /etc/xdg/foot/foot.ini
    mode: 0644
    owner: root
    group: root
