---
- name: Install sway stuff
  apt:
      name:
      - alacritty
      - fonts-dejavu

- name: ensures /etc/xdg/alacritty/ dir exists
  file:
    path: "/etc/xdg/alacritty/"
    mode: 0755
    owner: root
    group: root
    state: directory

- name: Install alacritty configuration
  copy:
    src: alacritty.yml
    dest: /etc/xdg/alacritty/alacritty.yml
    mode: 0644
    owner: root
    group: root
